### ISSUE TITLE
Fix connection error

### ISSUE THREAD

**Issue by wonderBH717** [wonderBH717/YLT_NFT_MARKETPLACE#1]
I can't connection from front-end to backend

**Comment by bh0717-dev** [comment]
That's no problem.
After reading your code, I found the error.
You need to insert api key.

**Comment by wonderBH717** [comment]
> That's no problem. After reading your code, I found the error. You need to insert api key.

**Comment by wonderBH717** [comment]
I have on

**Comment by bh0717-dev** [comment]
Okay, So I think you need to check your front-end code.
